import React, { useEffect, useMemo, useState } from 'react';
import { Link, Navigate, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Check, ChevronRight, Plus, Save, Search, Trash2 } from 'lucide-react';
import { fetchPatientVisit, fetchProducts, updatePatientVisit } from '../../services/api';
import { useStaffSession } from '../../services/adminSession';

export default function PatientDetails() {
  const { id } = useParams(); const session = useStaffSession(); const [visit, setVisit] = useState(null); const [products, setProducts] = useState([]); const [query, setQuery] = useState(''); const [category, setCategory] = useState('All'); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const navigate = useNavigate();
  useEffect(() => { Promise.all([fetchPatientVisit(id), fetchProducts()]).then(([v,p]) => { setVisit(v); setProducts(p); }).catch(e => setError(e.message)); }, [id]);
  const filtered = useMemo(() => products.filter(p => (category === 'All' || p.category === category) && `${p.name} ${p.product_code}`.toLowerCase().includes(query.toLowerCase())), [products, query, category]);
  if (!session || session.user?.role !== 'admin') return <Navigate to="/admin/login" replace />;
  if (error) return <div className="container clinic-page"><div className="form-alert">{error}</div></div>; if (!visit) return <div className="container clinic-page">Loading patient details…</div>;
  const set = e => setVisit({ ...visit, [e.target.name]: e.target.value });
  const add = p => { if (!visit.recommendations.some(r => r.product_id === p.id)) setVisit({ ...visit, recommendations: [...visit.recommendations, { product_id: p.id, name: p.name, product_code: p.product_code, category: p.category, image_url: p.image_url, price: p.price, quantity: 1, instructions: '', frequency: '', duration: '', timing: '', food_timing: '', additional_instructions: '' }] }); };
  const editRec = (index, field, value) => setVisit({ ...visit, recommendations: visit.recommendations.map((r,i) => i === index ? { ...r, [field]: value } : r) });
  const remove = index => { if (window.confirm(`Remove ${visit.recommendations[index].name} from this recommendation?`)) setVisit({ ...visit, recommendations: visit.recommendations.filter((_,i) => i !== index) }); };
  const save = async () => { try { setVisit(await updatePatientVisit(id, visit)); setMessage('Patient consultation and recommendations saved.'); } catch(e) { setError(e.response?.data?.message || e.message); } };
  const continueToPrint = async () => { if (!visit.recommendations.length) { setError('Select at least one product before continuing to print.'); return; } try { await updatePatientVisit(id, visit); navigate(`/admin/patients/${id}/print`); } catch(e) { setError(e.response?.data?.message || e.message); } };
  const details = [['Patient',visit.patient_name],['Mobile',visit.mobile],['Age / Gender',`${visit.age || '—'} / ${visit.gender || '—'}`],['Address',visit.address],['Main concern',visit.concern],['Medical conditions',visit.medical_conditions],['Allergies',visit.allergies],['Current medicines',visit.current_medicines],['Previous treatments',visit.previous_treatments],['Receptionist notes',visit.receptionist_notes],['Visit',new Date(visit.visit_at).toLocaleString()],['Status',visit.status]];
  return <section className="clinic-page"><div className="container"><Link to="/admin/patients" className="back-link no-print"><ArrowLeft size={16}/> Back to patients</Link><header className="clinic-heading"><div><h1 className="serif">Patient Consultation</h1><p>{visit.patient_name} · Visit #{visit.id}</p></div></header>
    {message && <div className="form-success no-print">{message}</div>}{error && <div className="form-alert no-print">{error}</div>}
    <div className="clinic-panel patient-detail-grid">{details.map(([k,v])=><div key={k}><small>{k}</small><p>{v || 'Not provided'}</p></div>)}</div>
    <div className="clinic-panel clinic-form"><h2 className="serif">Admin Consultation</h2><div className="form-grid"><label>Consultation notes<textarea name="consultation_notes" value={visit.consultation_notes} onChange={set}/></label><label>Diagnosis / assessment<textarea name="diagnosis" value={visit.diagnosis} onChange={set}/></label><label>Recommended treatment<textarea name="recommended_treatment" value={visit.recommended_treatment} onChange={set}/></label><label>Follow-up date<input type="date" name="follow_up_date" value={visit.follow_up_date || ''} onChange={set}/></label></div><label className="no-print">Private admin notes (never printed)<textarea name="private_admin_notes" value={visit.private_admin_notes} onChange={set}/></label></div>
    <div className="clinic-panel patient-products-panel"><div className="section-row"><div><h2 className="serif">Product Selection</h2><p>Choose products recommended for this patient.</p></div><span className="selected-product-count">{visit.recommendations.length} selected</span></div>
      <div className="patient-filters no-print"><div className="search-box"><Search size={17}/><input placeholder="Search product or code" value={query} onChange={e=>setQuery(e.target.value)}/></div><select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{[...new Set(products.map(p=>p.category))].map(c=><option key={c}>{c}</option>)}</select></div>
      <div className="patient-product-catalogue no-print">{filtered.map(p=>{const selectedIndex=visit.recommendations.findIndex(r=>r.product_id===p.id);const selected=selectedIndex>=0;return <article className={`patient-product-card ${selected?'is-selected':''}`} key={p.id}><img src={p.image_url} alt=""/><div><small>{p.category}</small><strong>{p.name}</strong><span>Code: {p.product_code}</span><b>₹{Number(p.price||0).toLocaleString('en-IN')}</b></div><button className={selected?'selected-product':''} onClick={()=>selected?remove(selectedIndex):add(p)}>{selected?<><Check/> Selected</>:<><Plus/> Select</>}</button></article>})}</div>
      <div className="selected-recommendations"><h3 className="serif">Recommended Products</h3>{visit.recommendations.length ? visit.recommendations.map((r,i)=><article className="recommendation-editor" key={r.product_id}><div className="recommendation-product"><img src={r.image_url} alt=""/><div><strong>{r.name}</strong><small>Code: {r.product_code}</small></div><button className="icon-button" onClick={()=>remove(i)} aria-label={`Remove ${r.name}`}><Trash2 size={17}/></button></div><div className="recommendation-fields"><label>Quantity<input type="number" min="1" value={r.quantity} onChange={e=>editRec(i,'quantity',e.target.value)}/></label><label>Usage / dosage<input value={r.instructions||''} onChange={e=>editRec(i,'instructions',e.target.value)} placeholder="How to use"/></label><label>Frequency<input value={r.frequency||''} onChange={e=>editRec(i,'frequency',e.target.value)} placeholder="e.g. Twice daily"/></label><label>Duration<input value={r.duration||''} onChange={e=>editRec(i,'duration',e.target.value)} placeholder="e.g. 30 days"/></label><label>Timing<select value={r.timing||''} onChange={e=>editRec(i,'timing',e.target.value)}><option value="">Select timing</option><option>Morning</option><option>Afternoon</option><option>Evening</option><option>Night</option></select></label><label>Food timing<select value={r.food_timing||''} onChange={e=>editRec(i,'food_timing',e.target.value)}><option value="">Not applicable</option><option>Before food</option><option>After food</option><option>With food</option></select></label><label className="wide-field">Additional instructions<input value={r.additional_instructions||''} onChange={e=>editRec(i,'additional_instructions',e.target.value)} placeholder="Precautions or other guidance"/></label></div></article>) : <p className="empty-state">Select products from the catalogue above.</p>}</div>
      <div className="patient-detail-actions"><button className="secondary-button" onClick={save}><Save size={17}/> Save Patient Record</button><button className="primary-button" onClick={continueToPrint}>Save & Continue to Print <ChevronRight size={17}/></button></div>
    </div></div></section>;
}
