import React, { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, FileDown, Printer } from 'lucide-react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { fetchPatientVisit, updatePatientVisit } from '../../services/api';
import { useStaffSession } from '../../services/adminSession';

const emptyConsent = { accepted:false, physical_signature:false, patient_signature:'', admin_signature:'', witness_signature:'', patient_questions:'', consented_at:'', version:1, locked:false };

export default function PatientPrintPreview(){
  const {id}=useParams(); const session=useStaffSession(); const [visit,setVisit]=useState(null); const [consent,setConsent]=useState(emptyConsent); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false);
  useEffect(()=>{fetchPatientVisit(id).then(v=>{setVisit(v);setConsent({...emptyConsent,...v.consent});}).catch(e=>setError(e.message));},[id]);
  if(!session||session.user?.role!=='admin')return <Navigate to="/admin/login" replace/>; if(!visit)return <div className="clinic-page container">{error||'Loading print preview…'}</div>;
  if(!visit.recommendations?.length)return <section className="clinic-page"><div className="container"><div className="clinic-panel empty-print-state"><h1 className="serif">Select products before printing</h1><p>The previous sample hairstyle selections were removed. Return to this patient and select the correct clinic products.</p><Link className="primary-button" to={`/admin/patients/${id}`}><ArrowLeft/>Back to Patient</Link></div></div></section>;
  const locked=Boolean(consent.locked); const change=(field,value)=>setConsent(c=>({...c,[field]:value}));
  const saveConsent=async(lock=false)=>{setError('');setMessage('');if(lock&&(!consent.accepted||!consent.physical_signature)){setError('Consent and confirmation of the printed patient signature are required before completing the consultation.');return;}setSaving(true);try{const updated={...visit,status:lock?'Completed':visit.status,consent:{...consent,patient_signature:'',admin_signature:'',witness_signature:'',consented_at:consent.accepted?(consent.consented_at||new Date().toISOString()):'',locked:lock||consent.locked}};const saved=await updatePatientVisit(id,updated);setVisit(saved);setConsent({...emptyConsent,...saved.consent});setMessage(lock?'Consultation completed and consent locked.':'Consent saved successfully.');}catch(e){setError(e.response?.data?.message||e.message);}finally{setSaving(false);}};
  const productPages=Array.from({length:Math.max(1,Math.ceil(visit.recommendations.length/6))},(_,page)=>visit.recommendations.slice(page*6,page*6+6));
  const visitDate=new Date(visit.visit_at).toLocaleDateString('en-IN');
  return <section className="print-preview-page"><div className="container print-preview-shell"><div className="print-toolbar no-print"><Link to={`/admin/patients/${id}`}><ArrowLeft/>Back to Patient</Link><div><button onClick={()=>window.print()}><Printer/>Print</button><button onClick={()=>window.print()}><FileDown/>Save as PDF</button><button className="complete-button" disabled={locked||saving} onClick={()=>saveConsent(true)}><CheckCircle2/>{locked?'Consultation Completed':'Complete Consultation'}</button></div></div>{message&&<div className="form-success no-print">{message}</div>}{error&&<div className="form-alert no-print">{error}</div>}
    {productPages.map((pageProducts,pageIndex)=><article className="a4-sheet recommendation-page visual-product-page" key={pageIndex}><header className="document-header"><div className="document-brand"><img src="/brand/dipali-wakale-logo.png" alt=""/><div><h1 className="serif">Dipali Wakale</h1><p>HAIR &amp; SKIN CARE</p></div></div><div><strong>Patient Product Recommendation</strong><span>Visit #{visit.id} · Page {pageIndex+1} of {productPages.length}</span></div></header><section className="visual-patient-strip"><div><small>PATIENT</small><strong>{visit.patient_name}</strong></div><div><small>MOBILE</small><span>{visit.mobile}</span></div><div><small>VISIT DATE</small><span>{new Date(visit.visit_at).toLocaleDateString('en-IN')}</span></div><div><small>FOLLOW-UP</small><span>{visit.follow_up_date||'Not scheduled'}</span></div></section><h2 className="serif visual-products-title">Recommended Products</h2><div className="visual-product-grid">{pageProducts.map((r,i)=><article className="visual-print-product" key={r.product_id}><img src={r.image_url} alt={r.name}/><div className="visual-product-copy"><span className="visual-product-number">{pageIndex*6+i+1}</span><strong>{r.name}</strong><small>Code: {r.product_code} · Qty: {r.quantity}</small><p>{r.instructions||'Use as directed.'}</p>{[r.frequency,r.duration,r.timing,r.food_timing].filter(Boolean).length>0&&<small>{[r.frequency,r.duration,r.timing,r.food_timing].filter(Boolean).join(' · ')}</small>}{r.additional_instructions&&<em>{r.additional_instructions}</em>}</div></article>)}</div>{pageIndex===productPages.length-1&&<footer className="visual-consultation-footer"><div><small>MAIN CONCERN</small><span>{visit.concern||'—'}</span></div><div><small>RECOMMENDED TREATMENT</small><span>{visit.recommended_treatment||'—'}</span></div></footer>}</article>)}
    <article className="a4-sheet consent-page media-consent-page"><header className="document-header"><div className="document-brand"><img src="/brand/dipali-wakale-logo.png" alt=""/><div><h1 className="serif">Dipali Wakale</h1><p>HAIR &amp; SKIN CARE</p></div></div><div><strong>Photo &amp; Video Consent</strong><span>Version {consent.version}</span></div></header><h2 className="serif consent-title">Consent to Use Treatment Photos and Videos</h2><div className="consent-wording"><p>I, <strong>{visit.patient_name}</strong>, on <strong>{visitDate}</strong>, voluntarily permit Dipali Wakale Clinic to photograph and record videos of my treatment, including before-and-after results, and to publish this content on the clinic website, social-media pages and promotional materials. My face and voice may be visible. I understand that this permission is optional, will not affect my treatment, and may be withdrawn for future use by contacting the clinic.</p></div><label className="consent-checkbox"><input type="checkbox" disabled={locked} checked={consent.accepted} onChange={e=>change('accepted',e.target.checked)}/><span>I have read and understood this form and consent to the public use described above.</span></label><label className="physical-signature no-print"><input type="checkbox" disabled={locked} checked={consent.physical_signature} onChange={e=>change('physical_signature',e.target.checked)}/><span>A physical patient signature will be collected on the printed form.</span></label><div className="physical-signature-lines"><div><span>Patient signature</span><span>Date</span></div><div><span>Clinic representative signature</span><span>Date</span></div></div><div className="consent-meta"><span>Consent date and time: {consent.consented_at?new Date(consent.consented_at).toLocaleString('en-IN'):'____________________'}</span><span>Recorded by: {consent.recorded_by||session.user.username}</span></div><button className="primary-button no-print save-consent" disabled={locked||saving} onClick={()=>saveConsent(false)}>{saving?'Saving…':'Save Consent'}</button></article>
  </div></section>;
}
